Bellavista/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('data/', include('gestion_datos.urls')), 
    path('dash/', include('dashboards.urls')),
    path('reportes/', include('gestion_reportes.urls')),  
    path('', include('inicio.urls')), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboards/urls.py
from django.urls import path, include
from . import views

app_name = 'dashboards'

urlpatterns = [
    path('data/', include('gestion_datos.urls')),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('filtrar_reportes/', views.filtrar_reportes, name='filtrar_reportes'),
    path('reportes/', views.reportes, name='reportes'),
    path('reportes/datos/', views.get_report_data, name='get_report_data'), 
    path('kpi/', views.obtener_promedio_problemas, name='obtener_promedio_problemas'),
    path("ubicaciones/", views.obtener_ubicaciones, name="obtener_ubicaciones"),
    path('mapa-reportes/', views.mapa_reportes, name='mapa_reportes'),
    path('api/trabajadores/', views.obtener_trabajadores, name='obtener_trabajadores'),
    path('api/marcos/', views.obtener_marcos, name='obtener_marcos'),
    path('api/tipo/', views.obtener_tipos_incidentes, name='obtener_tipos'),
    
]

gestion_datos/urls.py
from django.urls import path, include
from . import views

app_name = 'gestion_datos'

urlpatterns = [
    path('gestion_usuario/', views.gestion_usuario, name='gestion_usuario'),
    path('registrarUsuario/', views.registrarUsuario, name='registrar_usuario'),
    path('edicionUsuario/<str:rut>/', views.edicionUsuario, name='edicion_usuario'),
    path('eliminarUsuario/<str:rut>/', views.eliminarUsuario, name='eliminar_usuario'),
    path('gestion_problema/', views.gestion_problema, name='gestion_problema'),
    path('registrarProblema/', views.registrarProblema, name='registrar_problema'),
    path('edicionProblema/<str:id>/', views.edicionProblema, name='edicion_problema'),
    path('eliminarProblema/<str:id>/', views.eliminarProblema, name='eliminar_problema'),
    path('gestion_marco/', views.gestion_marcos, name='gestion_marco'),
    path('registrarMarco/', views.registrarMarco, name='registrar_marco'),
    path('edicionMarco/<str:id>/', views.edicionMarco, name='edicion_marco'),
    path('eliminarMarco/<str:id>/', views.eliminarMarco, name='eliminar_marco'),
]

gestion_reportes/urls.py
from django.urls import path, include
from . import views  
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .views import ver_reportes, editar_reporte 

app_name = 'gestion_reportes'

urlpatterns = [
    path('reporte/', views.reporte_view, name='reporte'),
    path('reporte_trabajador/', views.reporte_trabajador, name='reporte_trabajador'),
    path('reporte_exito/', views.reporte_exito, name='reporte_exito'),
    path('reportes/', ver_reportes, name='ver_reportes'),
    path('ver-imagen/<int:reporte_id>/', views.ver_imagen, name='ver_imagen'),
    path('reportes/editar/<int:id>/', editar_reporte, name='editar_reporte'),
    path('guardar_reportes/', views.ver_reportes, name='guardar_reportes'),
    path('actualizar_tarea/<int:tarea_id>/', views.actualizar_tarea, name='actualizar_tarea'),
    path('tareas/', views.lista_tareas, name='lista_tareas'),
    path('reportes_tareas/', views.reportes_tareas, name='reportes_tareas'),
    path('reportes_tareas/datos/', views.get_report_data, name='get_report_data'), 
    path('asignar-tarea/', views.asignar_tarea_ajax, name='asignar_tarea_ajax'),
    path('eliminar-asignacion/', views.eliminar_asignacion_ajax, name='eliminar_asignacion_ajax'),
    path('editar-asignacion/', views.editar_asignacion_ajax, name='editar_asignacion_ajax'),
    path('eliminar-tarea/', views.eliminar_tarea_ajax, name='eliminar_tarea_ajax'),
    path('editar-tarea/', views.editar_tarea_ajax, name='editar_tarea_ajax'),
    path('obtener-tabla-asignaciones/', views.obtener_tabla_asignaciones, name='obtener_tabla_asignaciones'),
    path('obtener-tabla-tareas/', views.obtener_tabla_tareas, name='obtener_tabla_tareas'),
    path('filtrar_tareas/', views.filtrar_tareas_ajax, name='filtrar_tareas_ajax'),
    path('crear_tarea/', views.crear_tarea_ajax, name='crear_tarea_ajax'),
    path('obtener-reportes-problemas-disponibles/', views.obtener_reportes_problemas_disponibles, name='obtener_reportes_problemas_disponibles'),
    path('obtener_tareas_predeterminadas/', views.obtener_tareas_predeterminadas, name='obtener_tareas_predeterminadas'),
    path('obtener_tareas_predeterminadas2/', views.obtener_tareas_predeterminadas2, name='obtener_tareas_predeterminadas2'),
    path('eliminar-reporte/<int:reporte_id>/', views.eliminar_reporte, name='eliminar_reporte'),
    #path('crearTarea',views.crearTareaView.as_view(),name='CrearTareaN')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inicio/urls.py
from django.urls import path, include
from . import views  
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'inicio'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('inicio_admin/', views.inicio_admin, name='inicio_admin'),
    path('trabajador/', views.trabajador, name='trabajador'),
    path('editar_perfil/', views.editar_perfil, name='editar_perfil'),  
    path('recuperar_contrasena/', views.recuperar_contrasena, name='recuperar_contrasena'),  
    path('contacto/', views.contacto, name='contacto'), 
    path('nosotros/', views.nosotros, name='nosotros'), 
    path('login/', views.login_view, name='login'), 
    path('logout/', views.logout_view, name='logout'),
    path('administrador/', views.administrador, name='administrador'),  
    path('enviar_enlace/', views.enviar_enlace_view, name='enviar_enlace'),  
    path('recuperar_contrasena/codigo/<str:codigo>/', views.recuperar_contrasena_codigo, name='recuperar_contrasena_codigo'),  
    path('contactar_admin/', views.contactar_admin_view, name='contactar_admin'),  
    path('recuperar_contrasena/enviar_enlace/', views.enviar_enlace_view, name='enviar_enlace'),
    path('recuperar_contrasena/contactar_admin/', views.contactar_admin_view, name='contactar_admin'),
    path('recuperar_contrasena/', views.enviar_enlace_view, name='recuperar_contrasena'),
    path('recuperar-contrasena/<str:codigo>/', views.recuperar_contrasena_codigo, name='recuperar_contrasena_codigo'),
    path('actualizar_tarea/<int:tarea_id>/', views.actualizar_tarea, name='actualizar_tarea'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestion_datos/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, Group, Permission


class Rol(models.Model):
    id_rol = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()

    def _str_(self):
        return self.nombre


# ----------------------------- USUARIOS ---------------------------------
class UsuariosManager(BaseUserManager):
    def create_user(self, rut, password=None, **extra_fields):
        if not rut:
            raise ValueError(_('El RUT debe ser proporcionado'))
        user = self.model(rut=rut, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, rut, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(rut, password, **extra_fields)

class Usuarios(AbstractBaseUser, PermissionsMixin):
    rut = models.CharField(max_length=9, primary_key=True)
    nombre = models.CharField(max_length=100)
    apellido_p = models.CharField(max_length=100)
    apellido_m = models.CharField(max_length=100)
    fecha_n = models.DateField()
    rol = models.ForeignKey(Rol, on_delete=models.CASCADE, db_column='id_rol')
    correo = models.EmailField(max_length=150, unique=True, null=True, blank=True)  # Opcional para trabajadores
    telefono = models.CharField(max_length=15)    
    password = models.CharField(max_length=255)
    codigo_recuperacion = models.CharField(max_length=6, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

# Añade related_name para evitar conflicto con auth.User
    groups = models.ManyToManyField(
        Group,
        related_name='usuarios_gestion_groups',  # Cambia related_name para evitar conflictos
        blank=True
    )
    user_permissions = models.ManyToManyField(
        Permission,
        related_name='usuarios_gestion_permissions',  # Cambia related_name para evitar conflictos
        blank=True
    )

    objects = UsuariosManager()

    USERNAME_FIELD = 'rut'
    REQUIRED_FIELDS = ['telefono']  

    def __str__(self):
        return str(self.rut)

    def __str__(self):
        return f'{self.nombre} {self.apellido_p} {self.apellido_m}'

    def full_name(self):
        return f"{self.nombre} {self.apellido_p} {self.apellido_m}"

class Problemas(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(max_length=100)

class Marcos(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=40)
    descripcion = models.TextField(max_length=100)

    def __str__(self):
        return self.nombre  # Mostrar solo el nombre del marco
    
    class Meta:
        verbose_name = 'Marco'
        verbose_name_plural = 'Marcos'

class Historial_De_Cambios(models.Model):
    rut = models.ForeignKey(Usuarios, on_delete=models.CASCADE)
    tipo_cambio = models.CharField(max_length=100)
    fecha = models.DateField()

gestion_datos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Usuarios, Rol, Problemas, Marcos
from django.contrib import messages
from django.contrib.auth.hashers import make_password
from django.contrib import messages
from django.shortcuts import redirect

def gestion_usuario(request):
    UsuariosListados = Usuarios.objects.all()
    return render(request, "gestionUsuarios.html", {"usuarios": UsuariosListados})

def registrarUsuario(request):
    if request.method == "POST":
        rut = request.POST['txtRut']
        nombre = request.POST['txtNombre']
        apellido_p = request.POST['txtApellido_P']
        apellido_m = request.POST['txtApellido_M']
        fecha_n = request.POST['txtFecha_n']
        correo = request.POST['numCorreo']
        telefono = '+569' + request.POST['numTelefono']
        password = request.POST['numPassword']
        
       
        rol_id = request.POST['txtRol']
        try:
            rol_instance = Rol.objects.get(id_rol=rol_id) 
        except Rol.DoesNotExist:
            messages.error(request, 'Error: El rol seleccionado no existe.')
            return redirect('/data/gestion_usuario/')

  
        usuario = Usuarios.objects.create(
            rut=rut,
            nombre=nombre,
            apellido_p=apellido_p,
            apellido_m=apellido_m,
            fecha_n=fecha_n,
            rol=rol_instance,
            correo=correo,
            telefono=telefono,
            password=make_password(password) 
        )

        messages.success(request, '¡Usuario registrado!')
        return redirect('/data/gestion_usuario/')
    else:
        return redirect('/data/gestion_usuario/')
    
def edicionUsuario(request, rut):
    usuario = Usuarios.objects.get(rut=rut)
    
    if request.method == 'POST':
        cambios = False 
        
        if (request.POST['txtNombre'] != usuario.nombre or
            request.POST['txtApellido_P'] != usuario.apellido_p or
            request.POST['txtApellido_M'] != usuario.apellido_m or
            request.POST['txtFecha_n'] != str(usuario.fecha_n) or
            request.POST['numCorreo'] != usuario.correo or
            request.POST['numTelefono'] != usuario.telefono):
            cambios = True
        
        nueva_contraseña = request.POST.get('numPassword', '').strip()
        if nueva_contraseña:  
            cambios = True 
            usuario.password = make_password(nueva_contraseña)

        if not cambios:
            messages.error(request, 'Debe realizar cambios en alguno de los campos para guardar.')
            return redirect(f'/data/gestion_usuario/')
        
        usuario.nombre = request.POST['txtNombre']
        usuario.apellido_p = request.POST['txtApellido_P']
        usuario.apellido_m = request.POST['txtApellido_M']
        usuario.fecha_n = request.POST['txtFecha_n']
        usuario.correo = request.POST['numCorreo']
        
        telefono = request.POST['numTelefono']
        if not telefono.startswith('+569'):
            telefono = '+569' + telefono
        usuario.telefono = telefono
        
        usuario.save()
        
        messages.success(request, 'Usuario actualizado correctamente.')
        return redirect('/data/gestion_usuario/')
    
    return render(request, "gestionUsuarios.html")
                  
def eliminarUsuario(request, rut):
    usuario = get_object_or_404(Usuarios, rut=rut)
    usuario.delete()
    messages.success(request, '¡Usuario eliminado exitosamente!')
    return redirect('/data/gestion_usuario/')
##-----------------------PROBLEMAS-----------------------------
def gestion_problema(request):
    ProblemasListados = Problemas.objects.all()
    return render(request, "gestionProblemas.html", {"problemas": ProblemasListados})

def edicionProblema(request, id):
    problema = Problemas.objects.get(id=id)
    
    if request.method == 'POST':
        problema.nombre = request.POST['txtProblema']
        problema.descripcion = request.POST['txtDescripcion']
        problema.save()
        return redirect('/data/gestion_problema/')  

    return render(request, "edicionProblema.html", {"problema": problema})

def registrarProblema(request):
    if request.method == "POST":
        problema = request.POST['txtProblema']
        descripcion = request.POST['txtDescripcion']
       
        nuevo_problema = Problemas.objects.create(
            nombre=problema,
            descripcion=descripcion,
        )

        messages.success(request, '¡Problema registrado!')
        return redirect('/data/gestion_problema/') 
    else:
        return redirect('/data/gestion_problema/')  


def eliminarProblema(request, id):
    problema = Problemas.objects.get(id=id)
    problema.delete()

    messages.success(request, '¡Problema eliminado!')

    return redirect('/data/gestion_problema/')

##-----------------------MARCOS-----------------------------

def gestion_marcos(request):
    MarcosListados = Marcos.objects.all()
    return render(request, "gestionMarco.html", {"marcos": MarcosListados})

def edicionMarco(request, id):
    marco = Marcos.objects.get(id=id)
    
    if request.method == 'POST':
        marco.nombre = request.POST['txtMarco']
        marco.descripcion = request.POST['txtDescripcion']
        marco.save()
        return redirect('/data/gestion_marco/')  

    return render(request, "edicionMarco.html", {"marco": marco})

def registrarMarco(request):
    if request.method == "POST":
        marco = request.POST['txtMarco']
        descripcion = request.POST['txtDescripcion']
       
        nuevo_marco = Marcos.objects.create(
            nombre=marco,
            descripcion=descripcion,
        )

        messages.success(request, '¡Marco registrado!')
        return redirect('/data/gestion_marco/') 
    else:
        return redirect('/data/gestion_marco/')  


def eliminarMarco(request, id):
    marco = Marcos.objects.get(id=id)
    marco.delete()

    messages.success(request, '¡Marco eliminado!')

    return redirect('/data/gestion_marco/')

gestion_datos/templates/base_gestion_datos.html
<!DOCTYPE html>
<html lang="es">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Gestión de Datos{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/gestionDatos.css' %}">
    <style>
        body {
            margin: 0;
            padding: 0;
            background-image: url('/static/images/topography.png');
            background-repeat: repeat;
            background-position: top left;
            height: 100vh;
            background-size: auto;
        }
        .navbar-nav .nav-link {
        color: #fbfbfb; 
        }

        .navbar-nav .nav-link:hover {
        color: #3c46a0; 
        }

    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #2D6A8E;">
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/logogris.svg' %}" alt="Logo" style="height: 50px;">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" id="gestionDatosDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Gestión de Datos
                    </a>
                    <div class="dropdown-menu" aria-labelledby="gestionDatosDropdown">
                        <a class="dropdown-item" href="{% url 'gestion_datos:gestion_usuario' %}">Gestión de Usuarios</a>
                        <a class="dropdown-item" href="{% url 'gestion_datos:gestion_problema' %}">Gestión de Problemas</a>
                        <a class="dropdown-item" href="{% url 'gestion_datos:gestion_marco' %}">Gestión de Marcos</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'gestion_reportes:lista_tareas' %}">Control de Tareas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'gestion_reportes:ver_reportes' %}">Historial de Reportes</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" id="dashboardsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dashboards
                    </a>
                    <div class="dropdown-menu" aria-labelledby="gestionDatosDropdown">
                        <a class="dropdown-item" href="{% url 'dashboards:dashboard' %}">Dashboard Problemas</a>
                        <a class="dropdown-item" href="{% url 'dashboards:reportes' %}">Dashboard Asignaciones</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'dashboards:mapa_reportes' %}">Mapa</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'inicio:inicio_admin' %}">Inicio</a>
                </li>
                <li class="nav-item">
                    <form action="{% url 'inicio:logout' %}" method="post" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger logout-btn">Cerrar Sesión</button>
                    </form>
                </li>
            </ul>
        </div>
    </nav>
    
    <div class="container py-4">
        {% block body %}
        {% endblock %}
    </div>
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous">
    </script>
    <script src="{% static 'js/gestionDatos.js' %}"></script>
</body>

</html>

gestion_datos/templates/gestionMarco.html
{% extends "./base_gestion_datos.html" %}

{% block title %} Gestión de Marcos {% endblock %}

{% block body %}
<div class="row">
    <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-dismissible alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong class="text-dark">{{ message }}</strong>
        </div>
        {% endfor %}
        {% endif %}
        <h2>Gestión de Marcos</h2>
        <div class="card">
            <div class="card-body">
                <form action="/data/registrarMarco/" method="POST">{% csrf_token %}
                    <div class="form-group">
                        <input type="text" id="txtMarco" name="txtMarco" class="form-control" placeholder="Nombre del Marco"
                            maxlength="50" required>
                    </div>
                    <div class="form-group">
                        <input type="text" id="txtDescripcion" name="txtDescripcion" class="form-control" placeholder="Descripción"
                            maxlength="100" required>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success btn-block text-white">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-6 col-lg-8 col-xl-8">
        <h1>Listado de Marcos</h1>
        <div class="table-responsive py-2" style="max-height: 700px; overflow-y: auto;">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nombre</th>
                        <th>Descripción</th>
                        <th colspan="2">Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for m in marcos %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ m.nombre }}</td>
                        <td>{{ m.descripcion }}</td>
                        <td>
                            
                            <div class="d-flex justify-content-start">
                                <button class="btn btn-info mr-2" data-toggle="modal" data-target="#editMarcoModal{{ m.id }}">Editar</button>
                                <a href="/data/eliminarMarco/{{ m.id }}" class="btn btn-danger" onclick="return confirm('¿Estás seguro de que quieres eliminar a {{ m.nombre }}?')">Eliminar</a>
                            </div>
                        </td>
                    </tr>
    
                    <div class="modal fade" id="editMarcoModal{{ m.id }}" tabindex="-1" role="dialog" aria-labelledby="editMarcoModalLabel{{ m.id }}" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="editMarcoModalLabel{{ m.id }}">Edición de Marco</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <form action="/data/edicionMarco/{{ m.id }}/" method="POST">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <input type="text" id="txtMarco" name="txtMarco" value="{{ m.nombre }}" class="form-control" placeholder="Nombre del Marco" maxlength="50" required>
                                        </div>
                                        <div class="form-group">
                                            <input type="text" id="txtDescripcion" name="txtDescripcion" value="{{ m.descripcion }}" class="form-control" placeholder="Descripción" maxlength="100" required>
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-success btn-block text-white">Guardar</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    
{% endblock %}

gestion_datos/templates/gestionProblemas.html
{% extends "./base_gestion_datos.html" %}

{% block title %} Gestión de Problemas {% endblock %}

{% block body %}
<div class="row">
    <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-dismissible alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong class="text-dark">{{ message }}</strong>
        </div>
        {% endfor %}
        {% endif %}
        <h2>Gestión de Problemas</h2>
        <div class="card">
            <div class="card-body">
                <form action="/data/registrarProblema/" method="POST">{% csrf_token %}
                    <div class="form-group">
                        <input type="text" id="txtProblema" name="txtProblema" class="form-control" placeholder="Nombre"
                            maxlength="40" required>
                    </div>
                    <div class="form-group">
                        <input type="text" id="txtDescripcion" name="txtDescripcion" class="form-control" placeholder="Descripcion"
                            maxlength="40" required>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success btn-block text-white">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-6 col-lg-8 col-xl-8">
        <h1>Listado de Problemas</h1>
        <div class="table-responsive py-2" style="max-height: 600px; overflow-y: auto;">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>ID</th>
                        <th>Problema</th>
                        <th>Descripción</th>
                        <th colspan="2">Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for p in problemas %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ p.id }}</td>
                        <td>{{ p.nombre }}</td>
                        <td>{{ p.descripcion }}</td>
                        <td>
                   
                            <div class="d-flex justify-content-start">
                                <button class="btn btn-info mr-2" data-toggle="modal" data-target="#editProblemaModal{{ p.id }}">Editar</button>
                                <a href="/data/eliminarProblema/{{ p.id }}" class="btn btn-danger" onclick="return confirm('¿Estás seguro de que quieres eliminar a {{ p.nombre }}?')">Eliminar</a>
                            </div>
                        </td>
                    </tr>
    
                    <div class="modal fade" id="editProblemaModal{{ p.id }}" tabindex="-1" role="dialog" aria-labelledby="editProblemaModalLabel{{ p.id }}" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="editProblemaModalLabel{{ p.id }}">Edición de Problema</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <form action="/data/edicionProblema/{{ p.id }}/" method="POST">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <input type="text" id="txtProblema" name="txtProblema" value="{{ p.nombre }}" class="form-control" placeholder="Nombre del Problema" maxlength="20" required>
                                        </div>
                                        <div class="form-group">
                                            <input type="text" id="txtDescripcion" name="txtDescripcion" value="{{ p.descripcion }}" class="form-control" placeholder="Descripción" maxlength="40" required>
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-success btn-block text-white">Guardar</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
     
{% endblock %}